#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "calibreweb-nextgen"
name = "Calibre-Web-NextGen"
description.en = "Fully automate and simplify your eBook set up"

version = "4.1.32~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0-only"
admindoc = "https://github.com/new-usemame/Calibre-Web-NextGen/blob/main/README.md"
code = "https://github.com/new-usemame/Calibre-Web-NextGen"

fund = "https://ko-fi.com/calibrewebnextgen"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = true

disk = "400M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
    [resources.sources.main]
    url = "https://github.com/new-usemame/Calibre-Web-NextGen/archive/refs/tags/v4.1.33.tar.gz"
    sha256 = "3c9196bdd7dd7e511efeaa4a7e6e695a631f4830b645cc91fbfd7971745d168a"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^[vV](.*)$"

    [resources.sources.calibre]
    amd64.url = "https://github.com/YunoHost-Apps/calibreweb-automated_ynh/releases/download/v9.12.0/calibre-9.12.0-x86_64.txz"
    amd64.sha256 = "7cf8f5334503ac8f74b9e0b038c17df2dd2827405133ae7118f3aeb38e07ad76"
    arm64.url = "https://github.com/YunoHost-Apps/calibreweb-automated_ynh/releases/download/v9.12.0/calibre-9.12.0-arm64.txz"
    arm64.sha256 = "a7942d5d4a40ab02a4bf7503b058e17298b1fcff4491b460cf4e0a594c0f9197"

    extract = false
    rename = "calibre.txz"
    # We sync release from official repo https://github.com/kovidgoyal/calibre because they only keep the assets of latest version…
    autoupdate.upstream = "https://github.com/Thovi98/calibre-backup"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*x86_64.txz"
    autoupdate.asset.arm64 = ".*arm64.txz"

    [resources.sources.kepubify]
    arm64.url = "https://github.com/pgaskin/kepubify/releases/download/v4.0.4/kepubify-linux-arm64"
    arm64.sha256="5a15b8f6f6a96216c69330601bca29638cfee50f7bf48712795cff88ae2d03a3"
    armhf.url = "https://github.com/pgaskin/kepubify/releases/download/v4.0.4/kepubify-linux-arm"
    armhf.sha256 = "07f23275c4e674093443f01a591aa0980b0b87dbb0a10986d5001e9d56b0e1e7"
    i386.url = "https://github.com/pgaskin/kepubify/releases/download/v4.0.4/kepubify-linux-32bit"
    i386.sha256 = "3365a848ce06d43fca8f1999eb69c6c8e0e20a56b6b8658a8466b9726adef0f5"
    amd64.url = "https://github.com/pgaskin/kepubify/releases/download/v4.0.4/kepubify-linux-64bit"
    amd64.sha256 = "37d7628d26c5c906f607f24b36f781f306075e7073a6fe7820a751bb60431fc5"

    autoupdate.upstream = "https://github.com/pgaskin/kepubify"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "kepubify-linux-64bit"
    autoupdate.asset.i386 = "kepubify-linux-32bit"
    autoupdate.asset.armhf = "kepubify-linux-arm$"
    autoupdate.asset.arm64 = "kepubify-linux-arm64"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "eBook" ]


    [resources.permissions]
    main.url = "/"

    kobo.url = "/kobo"
    kobo.show_tile = false
    kobo.allowed = "visitors"
    kobo.protected = true

    opds.url = "/opds"
    opds.show_tile = false
    opds.allowed = "visitors"
    opds.protected = true

    kosync.url ="/kosync"
    kosync.show_tile = false
    kosync.allowed = "visitors"
    kosync.protected = true

    api.url = "/api/v3"
    api.show_tile = false
    api.allowed = "visitors"
    api.protected = true

    notes.url = "/api/UserStorage/Metadata"
    notes.show_tile = false
    notes.allowed = "visitors"
    notes.protected = true
    
    [resources.ports]
    main.default = 8083

    [resources.apt]
    packages = [
        "sqlite3",        # to tweak the database in the scripts
        "imagemagick",    # for cover extraction from EPUBs
        "python3-venv",   # for installing a venv environnement in the scripts
        "python3-dev",    # for compiling the ldap dependency during pip install
        "libldap2-dev",   # for compiling the ldap dependency during pip install
        "libsasl2-dev",   # for compiling the ldap dependency during pip install
        "libjpeg-dev",    # for comics and image reading in browser
        "build-essential", # for building lol
        "unrar-free",
        "zip",              # for creating the koplugin.zip during install and upgrade script
    ]
    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "libxml2-dev, libxslt1-dev";
    fi
    """

    [resources.nodejs]
    version = "24"
