#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

#This will backup the app.db file at the same time
ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

# NB: /var/log is not backuped during safety-backup-before-upgrades
ynh_backup "$data_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP FAIL2BAN CONFIGURATION
#=================================================

ynh_backup "/etc/fail2ban/jail.d/$app.conf"
ynh_backup "/etc/fail2ban/filter.d/$app.conf"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/"${app}".service"

#=================================================
# BACKUP THE DATA DIRECTORY
#=================================================

if ( [ ${do_not_backup_data:-0} -eq 1 ] || [ $BACKUP_CORE_ONLY -eq 1 ] )
    then
		if [ $BACKUP_CORE_ONLY -eq 1 ]
		then
		ynh_print_warn "Your electronic library will not be backed-up, because 'BACKUP_CORE_ONLY' is set. If you want to backup up $app with your library, please do a manual backup."
		else
		ynh_backup "$calibre_library_dir"
		fi
	fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
