#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================
get__calibre_library_dir() {
    ynh_app_setting_get --key=calibre_library_dir
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__calibre_library_dir() {
    ynh_app_setting_set --key=calibre_library_dir --value="$calibre_library_dir"
    sqlite3 $install_dir/config/app.db "UPDATE settings SET config_calibre_dir='$calibre_library_dir'"
}

#=================================================
ynh_app_config_run $1
