#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

calibre_library_dir="$data_dir/eBook"
ynh_app_setting_set --key="calibre_library_dir" --value="$calibre_library_dir"

calibre_config_dir="$install_dir/config/.config/calibre"
ynh_app_setting_set --key=calibre_config_dir --value=$calibre_config_dir

timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# CWNG sources
ynh_setup_source --dest_dir="$install_dir/build"

# Install kepubify converter
ynh_setup_source --dest_dir="$install_dir/tools" --source_id="kepubify"

# Install Calibre
ynh_setup_source --dest_dir="$install_dir/tools/calibre" --source_id="calibre"

pushd "$install_dir/tools/calibre"
	tar -xvf calibre.txz
popd

chown -R $app:$app $install_dir
chmod -R 770 $install_dir/tools

#=================================================
# CREATE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Creating files and directory..."

#build multimedia directory
ynh_multimedia_build_main_dir
ynh_multimedia_addaccess $app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

ynh_replace --match="engine = _session.bind" --replace="engine = _session.bind\n    create_admin_user(_session)" --file="$install_dir/build/cps/ub.py"

#Use sed because the command with ynh_replace doesn’t appear to change anything, and so was the previous patch
#ynh_replace --match="user.name = "admin"\n    user.email = "admin@example.org"\n    user.role = constants.ADMIN_USER_ROLES" --replace="user.name = "$admin"\n    user.email = "$admin_mail"\n    user.role = constants.ADMIN_USER_ROLES" --file="$install_dir/build/cps/ub.py"
sed -i \
    -e "s/user\.name = \"admin\"/user.name = \"$admin\"/" \
    -e "s/user\.email = \"admin@example\.org\"/user.email = \"$admin_mail\"/" \
    "$install_dir/build/cps/ub.py"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Setting up system configuration..."

#Cannot use empty string for X-script-name, causes an issue in the python prg
#https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx
if [ $path = "/" ] ; then
	ynh_replace --match="        proxy_set_header	X-Script-Name		__PATH__;" \
	            --replace="        proxy_set_header	X-Script-Name		/__PATH__;" \
	            --file="../conf/nginx.conf"
fi

#
if $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_replace --match="        proxy_set_header	X-Remote-User" \
	            --replace="#       proxy_set_header	X-Remote-User" \
	            --file="../conf/nginx.conf"
fi

# Create a dedicated nginx config
ynh_config_add_nginx


#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_script_progression "Building frontend..."

pushd "$install_dir"/build/frontend
	ynh_hide_warnings ynh_exec_as_app npm ci --quiet
	ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production npm cache clean --force
popd

ynh_script_progression "Building backend..."

pushd "$install_dir/build"
	ynh_exec_as_app python3 -m venv "$install_dir/build/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/build/venv/bin/pip" install --upgrade wheel pip setuptools
	ynh_hide_warnings ynh_exec_as_app "$install_dir/build/venv/bin/pip" install --no-cache-dir --upgrade --use-pep517 --only-deps "$install_dir/build"


	# Compile translations, otherwise we only have English
	ynh_hide_warnings bash scripts/compile_translations.sh
popd

chmod +x "$install_dir/build/scripts/"*.sh || true
chmod +x "$install_dir/build/scripts/"*.py || true
chmod 775 "$install_dir/build/cps/"*.py || true

pushd "$install_dir/build/scripts"
  CALIBRE_DBPATH="$install_dir/config" $install_dir/build/venv/bin/python3 auto_library.py
popd

ynh_script_progression "Add the koreader kosync extension..."
ynh_setup_source --dest_dir="$install_dir/build/cps/static" --source_id="kosync"

chown -R $app:$app "$install_dir"

# Remove unneeded files
ynh_safe_rm "$install_dir/build/.github"
ynh_safe_rm "$install_dir/build/README_images"
ynh_safe_rm "$install_dir/build/changelogs"
ynh_safe_rm "$install_dir/build/docs"
ynh_safe_rm "$install_dir/build/drafts"
ynh_safe_rm "$install_dir/build/examples"
ynh_safe_rm "$install_dir/build/feedback-server"
ynh_safe_rm "$install_dir/build/findings"
ynh_safe_rm "$install_dir/build/homepage"
ynh_safe_rm "$install_dir/build/kubernetes"
ynh_safe_rm "$install_dir/build/notes"
ynh_safe_rm "$install_dir/build/state"
ynh_safe_rm "$install_dir/build/tests"
ynh_safe_rm "$install_dir/build/wiki-src"
ynh_safe_rm "$install_dir/build/wiki_images"
ynh_safe_rm "$install_dir/build/wikisite"
ynh_safe_rm "$install_dir/build/.dockerignore"
ynh_safe_rm "$install_dir/build/.editorconfig"
ynh_safe_rm "$install_dir/build/.gitattributes"
ynh_safe_rm "$install_dir/build/.gitignore"
ynh_safe_rm "$install_dir/build/AI_README.md"
ynh_safe_rm "$install_dir/build/CHANGELOG.md"
ynh_safe_rm "$install_dir/build/CHANGES-vs-upstream.md"
ynh_safe_rm "$install_dir/build/CONTRIBUTING.md"
ynh_safe_rm "$install_dir/build/CONTRIBUTORS"
ynh_safe_rm "$install_dir/build/Dockerfile"
ynh_safe_rm "$install_dir/build/GOVERNANCE.md"
ynh_safe_rm "$install_dir/build/LICENSE"
ynh_safe_rm "$install_dir/build/README.md"
ynh_safe_rm "$install_dir/build/SECURITY.md"
ynh_safe_rm "$install_dir/build/babel.cfg"
ynh_safe_rm "$install_dir/build/build.sh"
ynh_safe_rm "$install_dir/build/docker-compose.yml"
ynh_safe_rm "$install_dir/build/docker-compose.yml.dev"
ynh_safe_rm "$install_dir/build/greptile.json"
ynh_safe_rm "$install_dir/build/messages.pot"
ynh_safe_rm "$install_dir/build/pytest.ini"
ynh_safe_rm "$install_dir/build/run_tests.sh"
  
#=================================================
# SETUP LOGROTATE
#=================================================
# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$log_file"
ynh_config_add_logrotate "$access_log_file"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression "Configuring Fail2Ban..."

# Make sure a log file exists (mostly for CI tests)
 if [ ! -f "$log_file" ]; then
	touch "$log_file"
	chown $app: "$log_file"
fi

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="$log_file" --failregex="^.*LDAP Login failed for user .* IP-address: <HOST>.*$"

#=================================================
# UPDATE DATABASE
#=================================================
ynh_script_progression "Updating database with the right values..."

_ynh_adapt_cwng_db

#=================================================
# SETUP SYSTEMD
#=================================================

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}" --template="systemd.service"

yunohost service add "${app}" --description="Calibre-Web-NextGen Browse eBook on the web" --log="$log_file"

#=================================================
# STARTING APP
#=================================================
ynh_script_progression "Start $app..."

ynh_systemctl --service="${app}" --action="start" --wait_until="Starting Gevent server on" -t 60

#Setting the proxy authentication in case calibre is not open to visitor.
#https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#login-via-header-from-upstream-authentication-source
#We need to update the sso login parameter, but for that the app needs to have run at least once to initialize the tables.
if ! $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_systemctl --service=$app --action="stop"
	sqlite3 $install_dir/config/app.db "UPDATE settings SET config_reverse_proxy_login_header_name='X-Remote-User', config_allow_reverse_proxy_header_login='True', config_allow_reverse_proxy_header_login=1 WHERE ID=1;"
	ynh_systemctl --service=$app --action="start" --wait_until="Starting Gevent server on"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
