#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove the service from the list of services known by Yunohost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "${app}" >/dev/null; then
	yunohost service remove "${app}"
fi

ynh_config_remove_systemd "${app}"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx web server configuration..."

ynh_config_remove_nginx

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

ynh_config_remove_logrotate

#=================================================
# REMOVE FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression "Removing Fail2Ban configuration..."

ynh_config_remove_fail2ban

ynh_script_progression "Removing log file..."

ynh_safe_rm "$log_file"
ynh_safe_rm "$access_log_file"

#=================================================
# MESSAGE TO USER
#=================================================
ynh_script_progression "Removal of $app completed"

# Warn about calibre_library_dir not removed if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ] && [ "$calibre_library_dir" != "$data_dir/eBook" ]; then
	ynh_print_info "The library folder "$calibre_library_dir" was not deleted. Delete it manually if required"
fi
