#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers


#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring nginx configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring $app's systemd service..."

ynh_restore "/etc/systemd/system/"${app}".service"

systemctl enable "${app}" --quiet

yunohost service add "${app}" --description="Calibre-Web-NextGen Browse eBook on the web" --log="$log_file"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE THE LOG FILE DIRECTORY
#=================================================

mkdir -p /var/log/$app
chown -R $app:$app /var/log/$app

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring library directory if required..."

ynh_restore "$calibre_library_dir" || true

#=================================================
# RESTORE THE MULTIMEDIA DIR IF NOT EXISTING
#=================================================
ynh_script_progression "Restoring the multimedia directory..."

ynh_multimedia_build_main_dir
ynh_multimedia_addaccess $app

#=================================================
# INITIALIZE DATA IF NOT EXISTING
#=================================================

if [ ! -e "$calibre_library_dir" ]; then
	ynh_print_info "Create calibre library folder $calibre_library_dir"
	mkdir -p $calibre_library_dir
	chown -R $app:$app $calibre_library_dir
fi

#=================================================
# RESTORE THE FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression "Restoring the Fail2Ban configuration..."

ynh_restore "/etc/fail2ban/jail.d/$app.conf"
ynh_restore "/etc/fail2ban/filter.d/$app.conf"

if [ ! -f "$log_file" ]; then
	touch "$log_file"
	chown $app: "$log_file"
fi

ynh_systemctl --action=restart --service=fail2ban

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting a systemd service..."

ynh_systemctl --service="${app}" --action="start" --wait_until="Starting Gevent server on" -t 60

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"

#=================================================
# WARNING FOR READ ACCESS
#=================================================
ynh_print_warn "Please, give required access to $app user to the $calibre_library_dir folder."
